version: '3'

services:
  python:
    build: .
    container_name: django_movies
    ports:
      - "${PYTHON_PORT}:8000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: sh -c 'python manage.py makemigrations; python manage.py migrate --settings=django_movies.settings.development; python manage.py runserver 0.0.0.0:8000 --settings=django_movies.settings.development'

  postgres:
    container_name: django_movies_db
    image: postgres:10-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
    
