# Generated by Django 3.1.7 on 2021-03-24 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210324_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='value',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='movie',
        ),
        migrations.RenameModel(
            old_name='Score',
            new_name='Calificacion',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Pais',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.pais'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='pelicula',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='movies.pelicula'),
            preserve_default=False,
        ),
    ]
