# Generated by Django 3.1.7 on 2021-03-25 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210324_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calificacion',
            new_name='Puntuacion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
